-- Matrundan produktions-preflight
--
-- Körs skrivskyddat mot produktionsdatabasen efter migration och före
-- publicering. Alla rader ska returnera ok = true. Därefter ska PostgRESTs
-- schema-cache laddas om och en autentiserad läsning av en verklig grupp göras.

WITH checks(name, ok) AS (
  VALUES
    ('read_rpc_current:get_group_app_state_v5h', to_regprocedure('public.get_group_app_state_v5h(uuid)') IS NOT NULL),
    ('read_rpc_fallback:get_group_app_state_v5g', to_regprocedure('public.get_group_app_state_v5g(uuid)') IS NOT NULL),
    ('visit_rpc:create_visit_with_review_v2', to_regprocedure('public.create_visit_with_review_v2(uuid,uuid,date,text,uuid[],smallint,smallint,smallint,smallint,text,text[])') IS NOT NULL),
    ('visit_rpc:selected-members-only', COALESCE(position('COALESCE(_participant_ids' IN pg_get_functiondef(to_regprocedure('public.create_visit_with_review_v2(uuid,uuid,date,text,uuid[],smallint,smallint,smallint,smallint,text,text[])'))) > 0 AND position('ARRAY[_uid]' IN pg_get_functiondef(to_regprocedure('public.create_visit_with_review_v2(uuid,uuid,date,text,uuid[],smallint,smallint,smallint,smallint,text,text[])'))) = 0 AND position('has_membership(_group_id, participant.user_id)' IN pg_get_functiondef(to_regprocedure('public.create_visit_with_review_v2(uuid,uuid,date,text,uuid[],smallint,smallint,smallint,smallint,text,text[])'))) > 0, false)),
    ('visit_rpc:guest-privacy', COALESCE(position('WHEN visit_row.is_original THEN' IN pg_get_functiondef(to_regprocedure('public.get_group_app_state_v5h(uuid)'))) > 0 AND position('visit_row.guests' IN pg_get_functiondef(to_regprocedure('public.get_group_app_state_v5h(uuid)'))) > 0 AND position('ELSE visit_row.guest_count' IN pg_get_functiondef(to_regprocedure('public.get_group_app_state_v5h(uuid)'))) > 0, false)),
    ('settings_rpc:replace_group_search_settings', to_regprocedure('public.replace_group_search_settings(uuid,jsonb,integer)') IS NOT NULL),
    ('settings_helper:search_area_label_is_broad', to_regprocedure('public.search_area_label_is_broad(text)') IS NOT NULL),
    ('search-area:broad-label-guard', COALESCE(position('search_area_label_is_broad' IN pg_get_functiondef(to_regprocedure('public.replace_group_search_settings(uuid,jsonb,integer)'))) > 0 AND position('has_group_role' IN pg_get_functiondef(to_regprocedure('public.replace_group_search_settings(uuid,jsonb,integer)'))) > 0 AND position('group_is_active' IN pg_get_functiondef(to_regprocedure('public.replace_group_search_settings(uuid,jsonb,integer)'))) > 0, false)),
    ('storage:visit-photo-limit', EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'visit-photos' AND name = 'visit-photos' AND public = false AND file_size_limit = 1500000 AND allowed_mime_types = ARRAY['image/jpeg']::text[])),
    ('create_rpc:create_group_with_owner_v2', to_regprocedure('public.create_group_with_owner_v2(text,text,jsonb,integer)') IS NOT NULL),
    ('place_rpc:create_or_link_provider_place_v5f', to_regprocedure('public.create_or_link_provider_place_v5f(uuid,text,text,text,text,text[],text[],text,text,text,double precision,double precision,text,text,jsonb)') IS NOT NULL),
    ('place_rpc:create_or_link_provider_places_batch_v1', to_regprocedure('public.create_or_link_provider_places_batch_v1(uuid,jsonb)') IS NOT NULL),
    ('place_rpc:link_provider_source_to_existing_place_v1', to_regprocedure('public.link_provider_source_to_existing_place_v1(uuid,uuid,text,text,text,text,text,double precision,double precision,jsonb)') IS NOT NULL),
    ('place_rpc:get_external_info_context_v1', to_regprocedure('public.get_place_external_info_context_v1(uuid,uuid)') IS NOT NULL),
    ('place_rpc:get_external_info_context_membership', COALESCE(position('has_membership' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v1(uuid,uuid)'))) > 0 AND position('provider = ''geoapify''' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v1(uuid,uuid)'))) > 0 AND position('status = ''active''' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v1(uuid,uuid)'))) > 0, false)),
    ('practical_info_rpc:update', to_regprocedure('public.update_group_place_practical_info_v1(uuid,uuid,text,jsonb,text,text)') IS NOT NULL),
    ('practical_info_rpc:get', to_regprocedure('public.get_group_place_practical_info_v1(uuid,uuid)') IS NOT NULL),
    ('practical_info_rpc:history', to_regprocedure('public.list_group_place_practical_info_history_v1(uuid,uuid,integer)') IS NOT NULL),
    ('practical_info_rpc:external-context-v2', to_regprocedure('public.get_place_external_info_context_v2(uuid,uuid)') IS NOT NULL),
    ('practical_info_rpc:save-snapshot', to_regprocedure('public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)') IS NOT NULL),
    ('practical_info_rpc:update-membership', COALESCE(position('has_membership' IN pg_get_functiondef(to_regprocedure('public.update_group_place_practical_info_v1(uuid,uuid,text,jsonb,text,text)'))) > 0 AND position('UPDATE public.group_places' IN pg_get_functiondef(to_regprocedure('public.update_group_place_practical_info_v1(uuid,uuid,text,jsonb,text,text)'))) > 0, false)),
    ('practical_info_rpc:snapshot-active-source', COALESCE(position('provider = ''geoapify''' IN pg_get_functiondef(to_regprocedure('public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)'))) > 0 AND position('status = ''active''' IN pg_get_functiondef(to_regprocedure('public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)'))) > 0 AND position('INSERT INTO public.place_external_info_snapshots' IN pg_get_functiondef(to_regprocedure('public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)'))) > 0, false)),
    ('cross_group_practical_info_rpc:get', to_regprocedure('public.get_cross_group_practical_info_suggestions_v1(uuid,uuid)') IS NOT NULL),
    ('cross_group_practical_info_rpc:apply', to_regprocedure('public.apply_cross_group_practical_info_suggestion_v1(uuid,uuid,text,text)') IS NOT NULL),
    ('cross_group_practical_info_rpc:privacy', COALESCE(position('gp.group_id <> _group_id' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) > 0 AND position('interval ''90 days''' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) > 0 AND position('''status'', ''conflicting''' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) > 0 AND position('sourceUrl' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) = 0 AND position('sourceNote' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) = 0 AND position('groupId' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) = 0 AND position('userId' IN pg_get_functiondef(to_regprocedure('public.cross_group_practical_info_candidate_v1(uuid,uuid,text)'))) = 0, false)),
    ('cross_group_practical_info_rpc:apply-revalidates', COALESCE(position('cross_group_practical_info_candidate_v1' IN pg_get_functiondef(to_regprocedure('public.apply_cross_group_practical_info_suggestion_v1(uuid,uuid,text,text)'))) > 0 AND position('fingerprint' IN pg_get_functiondef(to_regprocedure('public.apply_cross_group_practical_info_suggestion_v1(uuid,uuid,text,text)'))) > 0 AND position('group_place_practical_info_history' IN pg_get_functiondef(to_regprocedure('public.apply_cross_group_practical_info_suggestion_v1(uuid,uuid,text,text)'))) > 0, false)),
    ('place_trigger:resolve_missing_in_osm_reports', to_regprocedure('public.resolve_missing_in_osm_reports_for_active_source_v1()') IS NOT NULL),
    ('hidden_rpc:list', to_regprocedure('public.list_group_hidden_place_suggestions(uuid)') IS NOT NULL),
    ('hidden_rpc:list-v2', to_regprocedure('public.list_group_hidden_place_suggestions_v2(uuid)') IS NOT NULL),
    ('hidden_rpc:hide', to_regprocedure('public.hide_group_place_suggestion(uuid,text,text,text,text,text)') IS NOT NULL),
    ('hidden_rpc:hide-v2', to_regprocedure('public.hide_group_place_suggestion_v2(uuid,text,text,text,text,text,text,text,double precision,double precision,text)') IS NOT NULL),
    ('hidden_rpc:restore', to_regprocedure('public.restore_group_place_suggestion(uuid,text,text)') IS NOT NULL),
    ('place_data_report_rpc:create', to_regprocedure('public.create_place_data_report_v1(uuid,uuid,text,text)') IS NOT NULL),
    ('place_data_report_rpc:create-suggestion', to_regprocedure('public.create_place_data_report_from_suggestion_v1(uuid,text,text,text,text,text,text,double precision,double precision,text,text)') IS NOT NULL),
    ('place_data_report_rpc:list-v1', to_regprocedure('public.list_group_place_data_reports_v1(uuid)') IS NOT NULL),
    ('place_data_report_rpc:list-v2', to_regprocedure('public.list_group_place_data_reports_v2(uuid)') IS NOT NULL),
    ('place_data_report_rpc:list-v3', to_regprocedure('public.list_group_place_data_reports_v3(uuid)') IS NOT NULL),
    ('place_data_report_rpc:review', to_regprocedure('public.review_place_data_report_v1(uuid,uuid,text,text)') IS NOT NULL),
    ('place_data_report_rpc:suggestion-target-semantics', COALESCE(position('target_provider_place_id' IN pg_get_functiondef(to_regprocedure('public.create_place_data_report_from_suggestion_v1(uuid,text,text,text,text,text,text,double precision,double precision,text,text)'))) > 0 AND position('place_id' IN pg_get_functiondef(to_regprocedure('public.create_place_data_report_from_suggestion_v1(uuid,text,text,text,text,text,text,double precision,double precision,text,text)'))) > 0, false)),
    ('place_data_signal_rpc:get', to_regprocedure('public.get_place_data_signals_v1(uuid,jsonb)') IS NOT NULL),
    ('place_data_signal_rpc:confirm', to_regprocedure('public.confirm_place_data_signal_v1(uuid,uuid,text,text,text)') IS NOT NULL),
    ('place_data_signal_rpc:cross-group-only', COALESCE(position('report.group_id <> _group_id' IN pg_get_functiondef(to_regprocedure('public.get_place_data_signals_v1(uuid,jsonb)'))) > 0 AND position('confirmation.group_id <> _group_id' IN pg_get_functiondef(to_regprocedure('public.get_place_data_signals_v1(uuid,jsonb)'))) > 0, false)),
    ('place_data_signal_rpc:neutral-output', COALESCE(position('closureStatus' IN pg_get_functiondef(to_regprocedure('public.get_place_data_signals_v1(uuid,jsonb)'))) > 0 AND position('limitedInformation' IN pg_get_functiondef(to_regprocedure('public.get_place_data_signals_v1(uuid,jsonb)'))) > 0 AND position('recentlyConfirmedOpen' IN pg_get_functiondef(to_regprocedure('public.get_place_data_signals_v1(uuid,jsonb)'))) > 0, false)),
    ('osm_note_rpc:prepare', to_regprocedure('public.prepare_place_data_report_osm_submission_v1(uuid,uuid,text)') IS NOT NULL),
    ('osm_note_rpc:prepare-current-source-guard', COALESCE(position('Matstället har redan en aktiv OpenStreetMap-koppling' IN pg_get_functiondef(to_regprocedure('public.prepare_place_data_report_osm_submission_v1(uuid,uuid,text)'))) > 0, false)),
    ('osm_note_rpc:prepare-attempt-log-quota', COALESCE(position('place_data_report_osm_submission_attempts' IN pg_get_functiondef(to_regprocedure('public.prepare_place_data_report_osm_submission_v1(uuid,uuid,text)'))) > 0 AND position('osm-submit-user:' IN pg_get_functiondef(to_regprocedure('public.prepare_place_data_report_osm_submission_v1(uuid,uuid,text)'))) > 0 AND position('osm-submit-group:' IN pg_get_functiondef(to_regprocedure('public.prepare_place_data_report_osm_submission_v1(uuid,uuid,text)'))) > 0, false)),
    ('osm_note_rpc:complete', to_regprocedure('public.complete_place_data_report_osm_submission_v1(uuid,text,bigint,text,timestamptz,timestamptz,text)') IS NOT NULL),
    ('osm_note_rpc:fail', to_regprocedure('public.fail_place_data_report_osm_submission_v1(uuid,text,text)') IS NOT NULL),
    ('osm_note_rpc:get-refresh', to_regprocedure('public.get_place_data_report_osm_refresh_v1(uuid,uuid)') IS NOT NULL),
    ('osm_note_rpc:update-status', to_regprocedure('public.update_place_data_report_osm_status_v1(uuid,text,bigint,text,timestamptz)') IS NOT NULL),
    ('account_deletion:place_data_report_scrub', COALESCE(position('UPDATE public.place_data_reports' IN pg_get_functiondef(to_regprocedure('public.prepare_own_account_deletion(jsonb,boolean)'))) > 0 AND position('resolution_note = NULL' IN pg_get_functiondef(to_regprocedure('public.prepare_own_account_deletion(jsonb,boolean)'))) > 0, false)),
    ('account_deletion:osm_submitter_scrub', COALESCE(position('osm_submitted_by = NULL' IN pg_get_functiondef(to_regprocedure('public.prepare_own_account_deletion(jsonb,boolean)'))) > 0, false)),
    ('account_deletion:osm_attempt_submitter_scrub', COALESCE(position('place_data_report_osm_submission_attempts' IN pg_get_functiondef(to_regprocedure('public.prepare_own_account_deletion(jsonb,boolean)'))) > 0, false)),
    ('account_deletion:place_data_signal_delete', COALESCE(position('DELETE FROM public.place_data_signal_confirmations' IN pg_get_functiondef(to_regprocedure('public.prepare_own_account_deletion(jsonb,boolean)'))) > 0, false)),
    ('table:visit_guests', to_regclass('public.visit_guests') IS NOT NULL),
    ('table:group_search_areas', to_regclass('public.group_search_areas') IS NOT NULL),
    ('table:group_hidden_place_suggestions', to_regclass('public.group_hidden_place_suggestions') IS NOT NULL),
    ('table:place_data_reports', to_regclass('public.place_data_reports') IS NOT NULL),
    ('table:place_data_report_osm_submission_attempts', to_regclass('public.place_data_report_osm_submission_attempts') IS NOT NULL),
    ('table:place_data_signal_confirmations', to_regclass('public.place_data_signal_confirmations') IS NOT NULL),
    ('table:group_place_practical_info_history', to_regclass('public.group_place_practical_info_history') IS NOT NULL),
    ('table:place_external_info_snapshots', to_regclass('public.place_external_info_snapshots') IS NOT NULL),
    ('rls:visit_guests', COALESCE((SELECT c.relrowsecurity FROM pg_class c WHERE c.oid = to_regclass('public.visit_guests')), false)),
    ('rls:place_data_report_osm_submission_attempts', COALESCE((SELECT c.relrowsecurity FROM pg_class c WHERE c.oid = to_regclass('public.place_data_report_osm_submission_attempts')), false)),
    ('rls:place_data_signal_confirmations', COALESCE((SELECT c.relrowsecurity FROM pg_class c WHERE c.oid = to_regclass('public.place_data_signal_confirmations')), false)),
    ('rls:group_place_practical_info_history', COALESCE((SELECT c.relrowsecurity FROM pg_class c WHERE c.oid = to_regclass('public.group_place_practical_info_history')), false)),
    ('rls:place_external_info_snapshots', COALESCE((SELECT c.relrowsecurity FROM pg_class c WHERE c.oid = to_regclass('public.place_external_info_snapshots')), false)),
    ('column:groups.default_search_radius_km', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'groups' AND column_name = 'default_search_radius_km')),
    ('column:places.website', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'places' AND column_name = 'website')),
    ('column:group_places.website_override', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'website_override')),
    ('column:group_places.opening_hours_override', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'opening_hours_override')),
    ('column:group_places.practical_info_source_url', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'practical_info_source_url')),
    ('column:group_places.practical_info_source_note', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'practical_info_source_note')),
    ('column:group_places.practical_info_updated_by', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'practical_info_updated_by')),
    ('column:group_places.practical_info_updated_at', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'practical_info_updated_at')),
    ('column:group_places.website_cross_group_proposal_at', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'website_cross_group_proposal_at')),
    ('column:group_places.opening_hours_cross_group_proposal_at', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_places' AND column_name = 'opening_hours_cross_group_proposal_at')),
    ('column:place_sources.status', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_sources' AND column_name = 'status')),
    ('column:place_data_reports.place_id_nullable', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'place_id' AND is_nullable = 'YES')),
    ('column:place_data_reports.target_provider', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'target_provider')),
    ('column:place_data_reports.target_provider_place_id', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'target_provider_place_id')),
    ('column:group_hidden_place_suggestions.category', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_hidden_place_suggestions' AND column_name = 'category')),
    ('column:group_hidden_place_suggestions.area', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_hidden_place_suggestions' AND column_name = 'area')),
    ('column:group_hidden_place_suggestions.lat', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_hidden_place_suggestions' AND column_name = 'lat')),
    ('column:group_hidden_place_suggestions.lng', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_hidden_place_suggestions' AND column_name = 'lng')),
    ('column:group_hidden_place_suggestions.website', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'group_hidden_place_suggestions' AND column_name = 'website')),
    ('column:place_data_reports.osm_submission_state', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_submission_state')),
    ('column:place_data_reports.osm_public_reference', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_public_reference')),
    ('column:place_data_reports.osm_public_text', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_public_text')),
    ('column:place_data_reports.osm_note_id', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_note_id')),
    ('column:place_data_reports.osm_note_url', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_note_url')),
    ('column:place_data_reports.osm_note_status', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_note_status')),
    ('column:place_data_reports.osm_note_last_checked_at', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_note_last_checked_at')),
    ('column:place_data_reports.osm_submitted_by', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_data_reports' AND column_name = 'osm_submitted_by')),
    ('constraint:place_data_reports_target', EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.place_data_reports'::regclass AND conname = 'place_data_reports_target_check')),
    ('constraint:place_data_reports_missing_in_osm_category', COALESCE(position('missing_in_osm' IN pg_get_constraintdef((SELECT oid FROM pg_constraint WHERE conrelid = 'public.place_data_reports'::regclass AND conname = 'place_data_reports_category_check'))) > 0, false)),
    ('constraint:place_data_reports_opening_hours_category', COALESCE(position('wrong_opening_hours' IN pg_get_constraintdef((SELECT oid FROM pg_constraint WHERE conrelid = 'public.place_data_reports'::regclass AND conname = 'place_data_reports_category_check'))) > 0, false)),
    ('constraint:osm_attempt_report_number_unique', to_regclass('public.place_data_report_osm_attempt_report_number_uidx') IS NOT NULL),
    ('trigger:place_sources_resolve_missing_in_osm_reports', EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = 'public.place_sources'::regclass AND tgname = 'place_sources_resolve_missing_in_osm_reports' AND NOT tgisinternal)),
    ('trigger:resolve-current-source-semantics', COALESCE(position('category = ''missing_in_osm''' IN pg_get_functiondef(to_regprocedure('public.resolve_missing_in_osm_reports_for_active_source_v1()'))) > 0 AND position('status = ''resolved''' IN pg_get_functiondef(to_regprocedure('public.resolve_missing_in_osm_reports_for_active_source_v1()'))) > 0 AND position('osm_submission_state = ''submitting''' IN pg_get_functiondef(to_regprocedure('public.resolve_missing_in_osm_reports_for_active_source_v1()'))) > 0, false)),
    ('index:place_sources_active_provider_identity_uidx', to_regclass('public.place_sources_active_provider_identity_uidx') IS NOT NULL),
    ('index:place_sources_active_place_provider_uidx', to_regclass('public.place_sources_active_place_provider_uidx') IS NOT NULL),
    ('index:place_data_reports_active_reporter_issue_uidx', to_regclass('public.place_data_reports_active_reporter_issue_uidx') IS NOT NULL),
    ('index:place_data_reports_active_provider_issue_uidx', to_regclass('public.place_data_reports_active_provider_issue_uidx') IS NOT NULL),
    ('index:place_data_reports_osm_note_id_uidx', to_regclass('public.place_data_reports_osm_note_id_uidx') IS NOT NULL),
    ('index:place_data_reports_osm_public_reference_uidx', to_regclass('public.place_data_reports_osm_public_reference_uidx') IS NOT NULL),
    ('index:place_data_report_osm_attempts_submitter_idx', to_regclass('public.place_data_report_osm_attempts_submitter_idx') IS NOT NULL),
    ('index:place_data_report_osm_attempts_group_idx', to_regclass('public.place_data_report_osm_attempts_group_idx') IS NOT NULL),
    ('index:place_data_report_osm_attempts_report_idx', to_regclass('public.place_data_report_osm_attempts_report_idx') IS NOT NULL),
    ('index:place_data_signal_confirmations_user_place_uidx', to_regclass('public.place_data_signal_confirmations_user_place_uidx') IS NOT NULL),
    ('index:place_data_signal_confirmations_user_provider_uidx', to_regclass('public.place_data_signal_confirmations_user_provider_uidx') IS NOT NULL),
    ('index:place_data_signal_confirmations_place_idx', to_regclass('public.place_data_signal_confirmations_place_idx') IS NOT NULL),
    ('index:place_data_signal_confirmations_provider_idx', to_regclass('public.place_data_signal_confirmations_provider_idx') IS NOT NULL),
    ('index:group_place_practical_info_history_lookup_idx', to_regclass('public.group_place_practical_info_history_lookup_idx') IS NOT NULL),
    ('index:place_external_info_snapshots_provider_idx', to_regclass('public.place_external_info_snapshots_provider_idx') IS NOT NULL),
    ('index:group_places_cross_group_practical_info_idx', to_regclass('public.group_places_cross_group_practical_info_idx') IS NOT NULL),
    ('grant:authenticated-current-read', has_function_privilege('authenticated', 'public.get_group_app_state_v5h(uuid)', 'EXECUTE')),
    ('grant:authenticated-create-visit-v2', has_function_privilege('authenticated', 'public.create_visit_with_review_v2(uuid,uuid,date,text,uuid[],smallint,smallint,smallint,smallint,text,text[])', 'EXECUTE')),
    ('grant:authenticated-settings', has_function_privilege('authenticated', 'public.replace_group_search_settings(uuid,jsonb,integer)', 'EXECUTE')),
    ('grant:authenticated-provider-link', has_function_privilege('authenticated', 'public.create_or_link_provider_place_v5f(uuid,text,text,text,text,text[],text[],text,text,text,double precision,double precision,text,text,jsonb)', 'EXECUTE')),
    ('grant:authenticated-provider-batch-link', has_function_privilege('authenticated', 'public.create_or_link_provider_places_batch_v1(uuid,jsonb)', 'EXECUTE')),
    ('grant:authenticated-manual-source-link', has_function_privilege('authenticated', 'public.link_provider_source_to_existing_place_v1(uuid,uuid,text,text,text,text,text,double precision,double precision,jsonb)', 'EXECUTE')),
    ('grant:authenticated-place-external-info-context', has_function_privilege('authenticated', 'public.get_place_external_info_context_v1(uuid,uuid)', 'EXECUTE')),
    ('grant:authenticated-practical-info-update', has_function_privilege('authenticated', 'public.update_group_place_practical_info_v1(uuid,uuid,text,jsonb,text,text)', 'EXECUTE')),
    ('grant:authenticated-practical-info-get', has_function_privilege('authenticated', 'public.get_group_place_practical_info_v1(uuid,uuid)', 'EXECUTE')),
    ('grant:authenticated-practical-info-history', has_function_privilege('authenticated', 'public.list_group_place_practical_info_history_v1(uuid,uuid,integer)', 'EXECUTE')),
    ('grant:authenticated-external-info-v2', has_function_privilege('authenticated', 'public.get_place_external_info_context_v2(uuid,uuid)', 'EXECUTE')),
    ('grant:authenticated-cross-group-practical-info-get', has_function_privilege('authenticated', 'public.get_cross_group_practical_info_suggestions_v1(uuid,uuid)', 'EXECUTE')),
    ('grant:authenticated-cross-group-practical-info-apply', has_function_privilege('authenticated', 'public.apply_cross_group_practical_info_suggestion_v1(uuid,uuid,text,text)', 'EXECUTE')),
    ('grant:service-save-external-snapshot', has_function_privilege('service_role', 'public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)', 'EXECUTE')),
    ('grant:authenticated-hidden-list', has_function_privilege('authenticated', 'public.list_group_hidden_place_suggestions(uuid)', 'EXECUTE')),
    ('grant:authenticated-hidden-list-v2', has_function_privilege('authenticated', 'public.list_group_hidden_place_suggestions_v2(uuid)', 'EXECUTE')),
    ('grant:authenticated-hidden-hide', has_function_privilege('authenticated', 'public.hide_group_place_suggestion(uuid,text,text,text,text,text)', 'EXECUTE')),
    ('grant:authenticated-hidden-hide-v2', has_function_privilege('authenticated', 'public.hide_group_place_suggestion_v2(uuid,text,text,text,text,text,text,text,double precision,double precision,text)', 'EXECUTE')),
    ('grant:authenticated-hidden-restore', has_function_privilege('authenticated', 'public.restore_group_place_suggestion(uuid,text,text)', 'EXECUTE')),
    ('grant:authenticated-place-data-report-create', has_function_privilege('authenticated', 'public.create_place_data_report_v1(uuid,uuid,text,text)', 'EXECUTE')),
    ('grant:authenticated-place-data-report-create-suggestion', has_function_privilege('authenticated', 'public.create_place_data_report_from_suggestion_v1(uuid,text,text,text,text,text,text,double precision,double precision,text,text)', 'EXECUTE')),
    ('grant:authenticated-place-data-report-list-v1', has_function_privilege('authenticated', 'public.list_group_place_data_reports_v1(uuid)', 'EXECUTE')),
    ('grant:authenticated-place-data-report-list-v2', has_function_privilege('authenticated', 'public.list_group_place_data_reports_v2(uuid)', 'EXECUTE')),
    ('grant:authenticated-place-data-report-list-v3', has_function_privilege('authenticated', 'public.list_group_place_data_reports_v3(uuid)', 'EXECUTE')),
    ('grant:authenticated-place-data-report-review', has_function_privilege('authenticated', 'public.review_place_data_report_v1(uuid,uuid,text,text)', 'EXECUTE')),
    ('grant:authenticated-place-data-signal-get', has_function_privilege('authenticated', 'public.get_place_data_signals_v1(uuid,jsonb)', 'EXECUTE')),
    ('grant:authenticated-place-data-signal-confirm', has_function_privilege('authenticated', 'public.confirm_place_data_signal_v1(uuid,uuid,text,text,text)', 'EXECUTE')),
    ('grant:authenticated-osm-prepare', has_function_privilege('authenticated', 'public.prepare_place_data_report_osm_submission_v1(uuid,uuid,text)', 'EXECUTE')),
    ('grant:authenticated-osm-refresh-context', has_function_privilege('authenticated', 'public.get_place_data_report_osm_refresh_v1(uuid,uuid)', 'EXECUTE')),
    ('grant:service-osm-complete', has_function_privilege('service_role', 'public.complete_place_data_report_osm_submission_v1(uuid,text,bigint,text,timestamptz,timestamptz,text)', 'EXECUTE')),
    ('grant:service-osm-fail', has_function_privilege('service_role', 'public.fail_place_data_report_osm_submission_v1(uuid,text,text)', 'EXECUTE')),
    ('grant:service-osm-update-status', has_function_privilege('service_role', 'public.update_place_data_report_osm_status_v1(uuid,text,bigint,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-anon-current-read', NOT has_function_privilege('anon', 'public.get_group_app_state_v5h(uuid)', 'EXECUTE')),
    ('isolation:no-anon-create-visit-v2', NOT has_function_privilege('anon', 'public.create_visit_with_review_v2(uuid,uuid,date,text,uuid[],smallint,smallint,smallint,smallint,text,text[])', 'EXECUTE')),
    ('isolation:no-anon-search-area-helper', COALESCE(NOT has_function_privilege('anon', to_regprocedure('public.search_area_label_is_broad(text)'), 'EXECUTE'), false)),
    ('isolation:no-authenticated-search-area-helper', COALESCE(NOT has_function_privilege('authenticated', to_regprocedure('public.search_area_label_is_broad(text)'), 'EXECUTE'), false)),
    ('isolation:no-anon-manual-source-link', NOT has_function_privilege('anon', 'public.link_provider_source_to_existing_place_v1(uuid,uuid,text,text,text,text,text,double precision,double precision,jsonb)', 'EXECUTE')),
    ('isolation:no-anon-place-external-info-context', NOT has_function_privilege('anon', 'public.get_place_external_info_context_v1(uuid,uuid)', 'EXECUTE')),
    ('isolation:no-anon-practical-info-update', NOT has_function_privilege('anon', 'public.update_group_place_practical_info_v1(uuid,uuid,text,jsonb,text,text)', 'EXECUTE')),
    ('isolation:no-anon-practical-info-get', NOT has_function_privilege('anon', 'public.get_group_place_practical_info_v1(uuid,uuid)', 'EXECUTE')),
    ('isolation:no-anon-practical-info-history', NOT has_function_privilege('anon', 'public.list_group_place_practical_info_history_v1(uuid,uuid,integer)', 'EXECUTE')),
    ('isolation:no-anon-external-info-v2', NOT has_function_privilege('anon', 'public.get_place_external_info_context_v2(uuid,uuid)', 'EXECUTE')),
    ('isolation:no-anon-cross-group-practical-info-get', NOT has_function_privilege('anon', 'public.get_cross_group_practical_info_suggestions_v1(uuid,uuid)', 'EXECUTE')),
    ('isolation:no-anon-cross-group-practical-info-apply', NOT has_function_privilege('anon', 'public.apply_cross_group_practical_info_suggestion_v1(uuid,uuid,text,text)', 'EXECUTE')),
    ('isolation:no-anon-save-external-snapshot', NOT has_function_privilege('anon', 'public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-authenticated-save-external-snapshot', NOT has_function_privilege('authenticated', 'public.save_place_external_info_snapshot_v1(uuid,uuid,text,text,jsonb,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-anon-hidden-list-v2', NOT has_function_privilege('anon', 'public.list_group_hidden_place_suggestions_v2(uuid)', 'EXECUTE')),
    ('isolation:no-anon-hidden-hide-v2', NOT has_function_privilege('anon', 'public.hide_group_place_suggestion_v2(uuid,text,text,text,text,text,text,text,double precision,double precision,text)', 'EXECUTE')),
    ('isolation:no-anon-place-data-report-create-suggestion', NOT has_function_privilege('anon', 'public.create_place_data_report_from_suggestion_v1(uuid,text,text,text,text,text,text,double precision,double precision,text,text)', 'EXECUTE')),
    ('isolation:no-anon-place-data-signal-get', NOT has_function_privilege('anon', 'public.get_place_data_signals_v1(uuid,jsonb)', 'EXECUTE')),
    ('isolation:no-anon-place-data-signal-confirm', NOT has_function_privilege('anon', 'public.confirm_place_data_signal_v1(uuid,uuid,text,text,text)', 'EXECUTE')),
    ('isolation:no-anon-osm-source-trigger-function', NOT has_function_privilege('anon', 'public.resolve_missing_in_osm_reports_for_active_source_v1()', 'EXECUTE')),
    ('isolation:no-authenticated-osm-source-trigger-function', NOT has_function_privilege('authenticated', 'public.resolve_missing_in_osm_reports_for_active_source_v1()', 'EXECUTE')),
    ('isolation:no-authenticated-osm-complete', NOT has_function_privilege('authenticated', 'public.complete_place_data_report_osm_submission_v1(uuid,text,bigint,text,timestamptz,timestamptz,text)', 'EXECUTE')),
    ('isolation:no-authenticated-osm-fail', NOT has_function_privilege('authenticated', 'public.fail_place_data_report_osm_submission_v1(uuid,text,text)', 'EXECUTE')),
    ('isolation:no-authenticated-osm-update-status', NOT has_function_privilege('authenticated', 'public.update_place_data_report_osm_status_v1(uuid,text,bigint,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-authenticated-visit-guests-read', NOT has_table_privilege('authenticated', 'public.visit_guests', 'SELECT')),
    ('isolation:no-authenticated-visit-guests-write', NOT has_table_privilege('authenticated', 'public.visit_guests', 'INSERT')),
    ('isolation:no-authenticated-place-source-table-access', NOT has_table_privilege('authenticated', 'public.place_sources', 'SELECT')),
    ('isolation:no-authenticated-search-area-table-access', NOT has_table_privilege('authenticated', 'public.group_search_areas', 'SELECT')),
    ('isolation:no-authenticated-hidden-table-access', NOT has_table_privilege('authenticated', 'public.group_hidden_place_suggestions', 'SELECT')),
    ('isolation:no-authenticated-place-data-report-table-access', NOT has_table_privilege('authenticated', 'public.place_data_reports', 'SELECT')),
    ('isolation:no-authenticated-osm-attempt-log-read', NOT has_table_privilege('authenticated', 'public.place_data_report_osm_submission_attempts', 'SELECT')),
    ('isolation:no-authenticated-osm-attempt-log-write', NOT has_table_privilege('authenticated', 'public.place_data_report_osm_submission_attempts', 'INSERT')),
    ('isolation:no-authenticated-place-data-signal-read', NOT has_table_privilege('authenticated', 'public.place_data_signal_confirmations', 'SELECT')),
    ('isolation:no-authenticated-place-data-signal-write', NOT has_table_privilege('authenticated', 'public.place_data_signal_confirmations', 'INSERT')),
    ('isolation:no-authenticated-practical-history-read', NOT has_table_privilege('authenticated', 'public.group_place_practical_info_history', 'SELECT')),
    ('isolation:no-authenticated-practical-history-write', NOT has_table_privilege('authenticated', 'public.group_place_practical_info_history', 'INSERT')),
    ('isolation:no-authenticated-external-snapshot-read', NOT has_table_privilege('authenticated', 'public.place_external_info_snapshots', 'SELECT')),
    ('isolation:no-authenticated-external-snapshot-write', NOT has_table_privilege('authenticated', 'public.place_external_info_snapshots', 'INSERT'))
)
SELECT name, ok
FROM checks
ORDER BY name;
