-- Tillägg till Matrundans produktions-preflight för v1.26.0.
-- Körs skrivskyddat efter supabase/production-preflight.sql. Alla rader ska
-- returnera ok = true innan platsomsynken eller appversionen publiceras.

WITH checks(name, ok) AS (
  VALUES
    ('place_location_rpc:get_place_external_info_context_v3', to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)') IS NOT NULL),
    ('place_location_rpc:save_place_external_info_snapshot_v2', to_regprocedure('public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)') IS NOT NULL),
    ('place_location_rpc:apply_place_external_location_v1', to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)') IS NOT NULL),
    ('place_location_rpc:context-membership-and-source', COALESCE(position('has_membership' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)'))) > 0 AND position('gp.collection_status = ''active''' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)'))) > 0 AND position('ps.provider = ''geoapify''' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)'))) > 0 AND position('ps.status = ''active''' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)'))) > 0, false)),
    ('place_location_rpc:context-admin-capability-only', COALESCE(position('m.role IN (''owner'', ''admin'')' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)'))) > 0 AND position('canApplyLocation' IN pg_get_functiondef(to_regprocedure('public.get_place_external_info_context_v3(uuid,uuid)'))) > 0, false)),
    ('place_location_rpc:snapshot-active-source', COALESCE(position('ps.provider = ''geoapify''' IN pg_get_functiondef(to_regprocedure('public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0 AND position('ps.status = ''active''' IN pg_get_functiondef(to_regprocedure('public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0 AND position('INSERT INTO public.place_external_info_snapshots' IN pg_get_functiondef(to_regprocedure('public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0, false)),
    ('place_location_rpc:apply-admin-and-fresh-data', COALESCE(position('m.role IN (''owner'', ''admin'')' IN pg_get_functiondef(to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0 AND position('interval ''10 minutes''' IN pg_get_functiondef(to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0, false)),
    ('place_location_rpc:apply-locks-canonical-place', COALESCE(position('FOR UPDATE' IN pg_get_functiondef(to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0 AND position('UPDATE public.places' IN pg_get_functiondef(to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0, false)),
    ('place_location_rpc:apply-source-conflict-guards', COALESCE(position('Kartkällan är redan kopplad till ett annat matställe' IN pg_get_functiondef(to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0 AND position('Matstället har redan en annan aktiv OpenStreetMap-källa' IN pg_get_functiondef(to_regprocedure('public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)'))) > 0, false)),
    ('column:place_external_info_snapshots.address', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'address')),
    ('column:place_external_info_snapshots.area', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'area')),
    ('column:place_external_info_snapshots.city', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'city')),
    ('column:place_external_info_snapshots.lat', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'lat')),
    ('column:place_external_info_snapshots.lng', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'lng')),
    ('column:place_external_info_snapshots.osm_type', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'osm_type')),
    ('column:place_external_info_snapshots.osm_id', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'place_external_info_snapshots' AND column_name = 'osm_id')),
    ('constraint:place_external_info_snapshots_location_check', EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.place_external_info_snapshots'::regclass AND conname = 'place_external_info_snapshots_location_check')),
    ('grant:authenticated-location-context', has_function_privilege('authenticated', 'public.get_place_external_info_context_v3(uuid,uuid)', 'EXECUTE')),
    ('grant:authenticated-apply-location', has_function_privilege('authenticated', 'public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)', 'EXECUTE')),
    ('grant:service-save-location-snapshot', has_function_privilege('service_role', 'public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-anon-location-context', NOT has_function_privilege('anon', 'public.get_place_external_info_context_v3(uuid,uuid)', 'EXECUTE')),
    ('isolation:no-anon-apply-location', NOT has_function_privilege('anon', 'public.apply_place_external_location_v1(uuid,uuid,text,text,text,text,double precision,double precision,text,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-anon-save-location-snapshot', NOT has_function_privilege('anon', 'public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-authenticated-save-location-snapshot', NOT has_function_privilege('authenticated', 'public.save_place_external_info_snapshot_v2(uuid,uuid,text,text,jsonb,text,text,text,text,double precision,double precision,text,text,timestamptz)', 'EXECUTE')),
    ('isolation:no-authenticated-external-snapshot-read', NOT has_table_privilege('authenticated', 'public.place_external_info_snapshots', 'SELECT')),
    ('isolation:no-authenticated-external-snapshot-write', NOT has_table_privilege('authenticated', 'public.place_external_info_snapshots', 'INSERT'))
)
SELECT name, ok
FROM checks
ORDER BY name;
