import type { AppState } from "./types";
import { APP_VERSION } from "./version";

const today = new Date();
const daysAgo = (n: number) =>
  new Date(today.getTime() - n * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_STATE: AppState = {
  version: APP_VERSION,
  currentUserId: "m1",
  group: {
    id: "g1",
    name: "Fredagsgänget",
    emoji: "🍝",
    city: "Göteborg",
    createdAt: daysAgo(180),
    ownerId: "m1",
  },
  members: [
    { id: "m1", name: "Emilia", avatar: "🦊", role: "ägare" },
    { id: "m2", name: "Johan", avatar: "🐻", role: "admin" },
    { id: "m3", name: "Sara", avatar: "🐝", role: "medlem" },
    { id: "m4", name: "Viktor", avatar: "🦉", role: "medlem" },
    { id: "m5", name: "Nora", avatar: "🐿️", role: "medlem" },
  ],
  places: [
    {
      id: "p1",
      name: "Bhoga",
      category: "restaurang",
      cuisines: ["nordiskt", "smakmeny"],
      occasions: ["middag"],
      address: "Norra Hamngatan 10",
      city: "Göteborg",
      addedBy: "m1",
      addedAt: daysAgo(45),
      photo: "🌿",
      notes: "Sparade till en riktigt lång fredag.",
    },
    {
      id: "p2",
      name: "Da Matteo Vallgatan",
      category: "café",
      cuisines: ["kaffe", "surdeg"],
      occasions: ["snabbt", "avslappnat"],
      address: "Vallgatan 5",
      city: "Göteborg",
      addedBy: "m3",
      addedAt: daysAgo(120),
      photo: "☕",
    },
    {
      id: "p3",
      name: "Tacos & Tequila",
      category: "restaurang",
      cuisines: ["mexikanskt"],
      occasions: ["avslappnat"],
      address: "Andra Långgatan 22",
      city: "Göteborg",
      addedBy: "m2",
      addedAt: daysAgo(30),
      photo: "🌮",
    },
    {
      id: "p4",
      name: "Bröd & Salt",
      category: "bageri",
      cuisines: ["surdeg", "kanelbulle"],
      occasions: ["snabbt"],
      address: "Kungsportsavenyen 12",
      city: "Göteborg",
      addedBy: "m4",
      addedAt: daysAgo(60),
      photo: "🥐",
    },
    {
      id: "p5",
      name: "Koka",
      category: "restaurang",
      cuisines: ["nordiskt", "fine dining"],
      occasions: ["middag"],
      address: "Viktoriagatan 12",
      city: "Göteborg",
      addedBy: "m1",
      addedAt: daysAgo(15),
      photo: "⭐",
      notes: "Nyfikna på höstmenyn.",
    },
    {
      id: "p6",
      name: "Strömmingsluckan",
      category: "matvagn",
      cuisines: ["husmanskost", "fisk"],
      occasions: ["snabbt"],
      address: "Feskekôrka",
      city: "Göteborg",
      addedBy: "m5",
      addedAt: daysAgo(8),
      photo: "🐟",
    },
    {
      id: "p7",
      name: "Ölhallen 7:an",
      category: "pub",
      cuisines: ["öl", "pubmat"],
      occasions: ["avslappnat"],
      address: "Kungstorget 7",
      city: "Göteborg",
      addedBy: "m2",
      addedAt: daysAgo(75),
      photo: "🍺",
    },
    {
      id: "p8",
      name: "Max Nordstan",
      category: "snabbmat",
      cuisines: ["burgare"],
      occasions: ["snabbt"],
      address: "Nordstan",
      city: "Göteborg",
      addedBy: "m4",
      addedAt: daysAgo(3),
      photo: "🍔",
    },
  ],
  visits: [
    {
      id: "v1",
      placeId: "p2",
      date: daysAgo(5),
      meal: "fika",
      participantIds: ["m1", "m3"],
      overall: 5,
      taste: 5,
      value: 4,
      service: 5,
      comment: "Kardemummabullen var magisk.",
      createdBy: "m1",
    },
    {
      id: "v2",
      placeId: "p3",
      date: daysAgo(12),
      meal: "middag",
      participantIds: ["m1", "m2", "m4"],
      overall: 4,
      taste: 4,
      value: 5,
      service: 3,
      comment: "Tacosen räddade en trist tisdag.",
      createdBy: "m2",
    },
    {
      id: "v3",
      placeId: "p7",
      date: daysAgo(28),
      meal: "kväll",
      participantIds: ["m1", "m2", "m3", "m4", "m5"],
      overall: 4,
      comment: "Hela gänget samlat, mysigt.",
      createdBy: "m5",
    },
    {
      id: "v4",
      placeId: "p2",
      date: daysAgo(40),
      meal: "frukost",
      participantIds: ["m1"],
      overall: 4,
      createdBy: "m1",
    },
    {
      id: "v5",
      placeId: "p4",
      date: daysAgo(55),
      meal: "fika",
      participantIds: ["m4", "m5"],
      overall: 3,
      taste: 3,
      value: 4,
      service: 4,
      createdBy: "m4",
    },
  ],
  favorites: [
    { memberId: "m1", placeId: "p2" },
    { memberId: "m1", placeId: "p5" },
    { memberId: "m3", placeId: "p4" },
  ],
  activity: [
    {
      id: "a1",
      kind: "added",
      memberId: "m4",
      placeId: "p8",
      at: daysAgo(3),
      text: "Viktor la till Max Nordstan",
      target: { kind: "place", placeId: "p8" },
    },
    {
      id: "a2",
      kind: "visited",
      memberId: "m1",
      placeId: "p2",
      visitId: "v1",
      at: daysAgo(5),
      text: "Emilia registrerade ett besök på Da Matteo Vallgatan",
      target: { kind: "visit", placeId: "p2", visitId: "v1" },
    },
    {
      id: "a3",
      kind: "next-picked",
      memberId: "m2",
      placeId: "p5",
      at: daysAgo(2),
      text: "Johan valde Koka som nästa stopp",
      target: { kind: "place", placeId: "p5" },
    },
    {
      id: "a4",
      kind: "added",
      memberId: "m5",
      placeId: "p6",
      at: daysAgo(8),
      text: "Nora la till Strömmingsluckan",
      target: { kind: "place", placeId: "p6" },
    },
    {
      id: "a5",
      kind: "member-joined",
      memberId: "m5",
      at: daysAgo(20),
      text: "Nora gick med i gänget",
      target: { kind: "member", memberId: "m5" },
    },
  ],
  nextPlaceId: "p5",
};
