import type { AppState } from "./types";
import { APP_VERSION } from "./version";

const today = new Date();
const daysAgo = (days: number) =>
  new Date(today.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_STATE: AppState = {
  version: APP_VERSION,
  currentUserId: "m1",
  group: {
    id: "g1",
    name: "Fredagsgänget",
    emoji: "🍝",
    city: "Göteborg",
    createdAt: daysAgo(220),
    ownerId: "m1",
    homeLocation: {
      label: "Haga, Göteborg",
      verified: false,
    },
  },
  members: [
    { id: "m1", name: "Emilia", avatar: "🦊", role: "ägare" },
    { id: "m2", name: "Johan", avatar: "🐻", role: "admin" },
    { id: "m3", name: "Sara", avatar: "🐝", role: "medlem" },
    { id: "m4", name: "Viktor", avatar: "🦉", role: "medlem" },
    { id: "m5", name: "Nora", avatar: "🐿️", role: "medlem" },
  ],
  places: [
    {
      id: "p1",
      name: "Lilla Myntans Matrum",
      category: "restaurang",
      cuisines: ["nordiskt", "smakmeny"],
      occasions: ["middag"],
      address: "Myntgränden 8",
      area: "Inom Vallgraven",
      city: "Göteborg",
      lat: 57.7058,
      lng: 11.9676,
      addedBy: "m1",
      addedAt: daysAgo(52),
      photo: "🌿",
      notes: "Sparad till en fredag när alla kan stanna länge.",
      origin: "manual",
    },
    {
      id: "p2",
      name: "Kvarterets Kardemumma",
      category: "café",
      cuisines: ["kaffe", "surdeg", "bakverk"],
      occasions: ["snabbt", "avslappnat"],
      address: "Kanelgången 4",
      area: "Haga",
      city: "Göteborg",
      lat: 57.6996,
      lng: 11.9552,
      addedBy: "m3",
      addedAt: daysAgo(135),
      photo: "☕",
      origin: "provider",
    },
    {
      id: "p3",
      name: "Månskärans Taquería",
      category: "restaurang",
      cuisines: ["mexikanskt", "tacos"],
      occasions: ["avslappnat"],
      address: "Månskensgatan 12",
      area: "Linné",
      city: "Göteborg",
      lat: 57.6972,
      lng: 11.9491,
      addedBy: "m2",
      addedAt: daysAgo(38),
      photo: "🌮",
      origin: "provider",
    },
    {
      id: "p4",
      name: "Sju Smulors Bageri",
      category: "bageri",
      cuisines: ["surdeg", "kanelbulle"],
      occasions: ["snabbt", "avslappnat"],
      address: "Smultronvägen 7",
      area: "Vasastan",
      city: "Göteborg",
      lat: 57.6986,
      lng: 11.9627,
      addedBy: "m4",
      addedAt: daysAgo(68),
      photo: "🥐",
      origin: "manual",
    },
    {
      id: "p5",
      name: "Glöd & Grönska",
      category: "restaurang",
      cuisines: ["vegetariskt", "grillat"],
      occasions: ["middag"],
      address: "Grönskans gränd 3",
      area: "Vasastan",
      city: "Göteborg",
      lat: 57.6969,
      lng: 11.9588,
      addedBy: "m1",
      addedAt: daysAgo(18),
      photo: "🔥",
      notes: "Nästa stopp? Menyn ser ut att passa hela gänget.",
      origin: "provider",
    },
    {
      id: "p6",
      name: "Kajkantens Fisklucka",
      category: "matvagn",
      cuisines: ["fisk", "husmanskost"],
      occasions: ["snabbt"],
      address: "Kajpromenaden 2",
      area: "Rosenlund",
      city: "Göteborg",
      lat: 57.7008,
      lng: 11.9517,
      addedBy: "m5",
      addedAt: daysAgo(9),
      photo: "🐟",
      origin: "provider",
    },
    {
      id: "p7",
      name: "Kopparlyktan",
      category: "pub",
      cuisines: ["pubmat", "svenskt"],
      occasions: ["avslappnat"],
      address: "Lyktgränden 5",
      area: "Inom Vallgraven",
      city: "Göteborg",
      lat: 57.7069,
      lng: 11.9702,
      addedBy: "m2",
      addedAt: daysAgo(82),
      photo: "🍺",
      origin: "manual",
    },
    {
      id: "p8",
      name: "Nattugglans Nudlar",
      category: "snabbmat",
      cuisines: ["nudlar", "asiatiskt"],
      occasions: ["snabbt"],
      address: "Okänd tvärgata nära centrum",
      city: "Göteborg",
      addedBy: "m4",
      addedAt: daysAgo(4),
      photo: "🍜",
      notes: "Manuellt tillagt utan kartposition för att testa reservläget.",
      origin: "manual",
    },
    {
      id: "p9",
      name: "Solsidans Sopplunch",
      category: "restaurang",
      cuisines: ["soppa", "vegetariskt"],
      occasions: ["snabbt", "avslappnat"],
      address: "Solgläntan 14",
      area: "Majorna",
      city: "Göteborg",
      lat: 57.6961,
      lng: 11.9247,
      addedBy: "m5",
      addedAt: daysAgo(28),
      photo: "🥣",
      origin: "provider",
    },
  ],
  visits: [
    {
      id: "v1",
      placeId: "p2",
      date: daysAgo(5),
      meal: "fika",
      participantIds: ["m1", "m3"],
      overall: 5,
      taste: 5,
      value: 4,
      service: 5,
      comment: "Kardemummabullen vann hela eftermiddagen.",
      createdBy: "m1",
    },
    {
      id: "v2",
      placeId: "p3",
      date: daysAgo(13),
      meal: "middag",
      isTakeaway: true,
      participantIds: ["m1", "m2", "m4"],
      overall: 4,
      taste: 4,
      value: 5,
      service: 3,
      comment: "Bra delningsrätter hemma runt köksbordet.",
      createdBy: "m2",
    },
    {
      id: "v3",
      placeId: "p7",
      date: daysAgo(31),
      meal: "kväll",
      participantIds: ["m1", "m2", "m3", "m4", "m5"],
      overall: 4,
      comment: "Första kvällen med hela gänget samlat.",
      createdBy: "m5",
    },
    {
      id: "v4",
      placeId: "p2",
      date: daysAgo(44),
      meal: "frukost",
      participantIds: ["m1"],
      overall: 4,
      createdBy: "m1",
    },
    {
      id: "v5",
      placeId: "p4",
      date: daysAgo(57),
      meal: "fika",
      participantIds: ["m4", "m5"],
      overall: 3,
      taste: 4,
      value: 3,
      service: 4,
      createdBy: "m4",
    },
    {
      id: "v6",
      placeId: "p2",
      date: daysAgo(91),
      meal: "fika",
      participantIds: ["m1", "m2", "m3"],
      overall: 5,
      taste: 5,
      value: 4,
      service: 4,
      comment: "Tredje rundan bekräftade att det är ett riktigt stammisställe.",
      createdBy: "m3",
    },
    {
      id: "v7",
      placeId: "p9",
      date: daysAgo(20),
      meal: "lunch",
      participantIds: ["m2", "m5"],
      overall: 4,
      taste: 4,
      value: 5,
      service: 4,
      createdBy: "m5",
    },
    {
      id: "v8",
      placeId: "p7",
      date: daysAgo(16),
      meal: "dryck",
      participantIds: ["m1", "m2"],
      overall: 0,
      comment: "En öl och lång pratstund efter jobbet.",
      createdBy: "m2",
    },
  ],
  favorites: [
    { memberId: "m1", placeId: "p2" },
    { memberId: "m3", placeId: "p2" },
    { memberId: "m1", placeId: "p5" },
    { memberId: "m2", placeId: "p3" },
    { memberId: "m4", placeId: "p4" },
    { memberId: "m5", placeId: "p9" },
  ],
  activity: [
    {
      id: "a1",
      kind: "added",
      memberId: "m4",
      placeId: "p8",
      at: daysAgo(4),
      text: "Viktor la till Nattugglans Nudlar",
      target: { kind: "place", placeId: "p8" },
    },
    {
      id: "a2",
      kind: "visited",
      memberId: "m1",
      placeId: "p2",
      visitId: "v1",
      at: daysAgo(5),
      text: "Emilia registrerade ett besök på Kvarterets Kardemumma",
      target: { kind: "visit", placeId: "p2", visitId: "v1" },
    },
    {
      id: "a3",
      kind: "next-picked",
      memberId: "m2",
      placeId: "p5",
      at: daysAgo(2),
      text: "Johan valde Glöd & Grönska som nästa stopp",
      target: { kind: "place", placeId: "p5" },
    },
    {
      id: "a4",
      kind: "added",
      memberId: "m5",
      placeId: "p6",
      at: daysAgo(9),
      text: "Nora la till Kajkantens Fisklucka",
      target: { kind: "place", placeId: "p6" },
    },
    {
      id: "a5",
      kind: "member-joined",
      memberId: "m5",
      at: daysAgo(24),
      text: "Nora gick med i gänget",
      target: { kind: "member", memberId: "m5" },
    },
  ],
  nextPlaceId: "p5",
};
