import type { AppState } from "./types";
import { APP_VERSION } from "./version";

const today = new Date();
const daysAgo = (days: number) =>
  new Date(today.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

/**
 * Publik, skrivskyddad exempelgrupp.
 *
 * Matställena är verkliga Stockholm-ställen. Medlemmar, besök, betyg,
 * kommentarer, favoriter och aktivitet är helt fiktiva exempeldata.
 */
export const EXAMPLE_STATE: AppState = {
  version: APP_VERSION,
  currentUserId: "m1",
  group: {
    id: "example-stockholm",
    name: "Fredagsgänget",
    emoji: "🍝",
    city: "Stockholm",
    createdAt: daysAgo(240),
    ownerId: "m1",
    homeLocation: {
      label: "Stockholm",
      verified: false,
    },
  },
  members: [
    { id: "m1", name: "Alex", avatar: "🦊", role: "ägare" },
    { id: "m2", name: "Sam", avatar: "🐻", role: "admin" },
    { id: "m3", name: "Robin", avatar: "🐝", role: "medlem" },
    { id: "m4", name: "Kim", avatar: "🦉", role: "medlem" },
    { id: "m5", name: "Noor", avatar: "🐿️", role: "medlem" },
  ],
  places: [
    {
      id: "p1",
      name: "Pelikan",
      category: "restaurang",
      cuisines: ["svenskt", "husmanskost"],
      occasions: ["middag"],
      address: "Blekingegatan 40",
      area: "Södermalm",
      city: "Stockholm",
      lat: 59.3109,
      lng: 18.074,
      addedBy: "m2",
      addedAt: daysAgo(150),
      photo: "🍽️",
      notes: "Ett klassiskt stopp när hela gänget kan ses över middag.",
      origin: "provider",
    },
    {
      id: "p2",
      name: "Café Pascal",
      category: "café",
      cuisines: ["kaffe", "bakverk"],
      occasions: ["snabbt", "avslappnat"],
      address: "Norrtullsgatan 4",
      area: "Vasastan",
      city: "Stockholm",
      lat: 59.3408,
      lng: 18.0501,
      addedBy: "m3",
      addedAt: daysAgo(138),
      photo: "☕",
      origin: "provider",
    },
    {
      id: "p3",
      name: "La Neta City",
      category: "restaurang",
      cuisines: ["mexikanskt", "tacos"],
      occasions: ["avslappnat"],
      address: "Barnhusgatan 2",
      area: "Norrmalm",
      city: "Stockholm",
      lat: 59.335,
      lng: 18.0571,
      addedBy: "m2",
      addedAt: daysAgo(112),
      photo: "🌮",
      origin: "provider",
    },
    {
      id: "p4",
      name: "Lillebrors Bageri",
      category: "bageri",
      cuisines: ["surdeg", "bakverk"],
      occasions: ["snabbt", "avslappnat"],
      address: "Rörstrandsgatan 10",
      area: "Vasastan",
      city: "Stockholm",
      lat: 59.3406,
      lng: 18.0359,
      addedBy: "m4",
      addedAt: daysAgo(94),
      photo: "🥐",
      origin: "provider",
    },
    {
      id: "p5",
      name: "Hermans",
      category: "restaurang",
      cuisines: ["vegetariskt", "veganskt"],
      occasions: ["avslappnat", "middag"],
      address: "Fjällgatan 23B",
      area: "Södermalm",
      city: "Stockholm",
      lat: 59.3172,
      lng: 18.091,
      addedBy: "m1",
      addedAt: daysAgo(20),
      photo: "🌿",
      notes: "Nästa stopp – utsikten och det vegetariska utbudet känns rätt för gänget.",
      origin: "provider",
    },
    {
      id: "p6",
      name: "Meatballs for the People",
      category: "restaurang",
      cuisines: ["svenskt", "husmanskost"],
      occasions: ["middag"],
      address: "Nytorgsgatan 30",
      area: "Södermalm",
      city: "Stockholm",
      lat: 59.312,
      lng: 18.0814,
      addedBy: "m5",
      addedAt: daysAgo(70),
      photo: "🧆",
      origin: "provider",
    },
    {
      id: "p7",
      name: "Falloumi",
      category: "snabbmat",
      cuisines: ["falafel", "vegetariskt"],
      occasions: ["snabbt", "avslappnat"],
      address: "Ringvägen 127",
      area: "Södermalm",
      city: "Stockholm",
      lat: 59.3078,
      lng: 18.0787,
      addedBy: "m4",
      addedAt: daysAgo(48),
      photo: "🥙",
      origin: "provider",
    },
    {
      id: "p8",
      name: "K25",
      category: "snabbmat",
      cuisines: ["street food", "asiatiskt"],
      occasions: ["snabbt"],
      address: "Kungsgatan 25",
      area: "Norrmalm",
      city: "Stockholm",
      lat: 59.3361,
      lng: 18.0643,
      addedBy: "m1",
      addedAt: daysAgo(34),
      photo: "🍜",
      origin: "provider",
    },
    {
      id: "p9",
      name: "Restaurang Kvarnen",
      category: "pub",
      cuisines: ["svenskt", "husmanskost", "pubmat"],
      occasions: ["avslappnat", "middag"],
      address: "Tjärhovsgatan 4",
      area: "Södermalm",
      city: "Stockholm",
      lat: 59.3143,
      lng: 18.0777,
      addedBy: "m5",
      addedAt: daysAgo(58),
      photo: "🍺",
      origin: "provider",
    },
  ],
  visits: [
    {
      id: "v1",
      placeId: "p2",
      date: daysAgo(6),
      meal: "fika",
      participantIds: ["m1", "m3"],
      overall: 5,
      taste: 5,
      value: 4,
      service: 5,
      comment: "En lugn fredagsfika och en riktigt bra kardemummabulle.",
      createdBy: "m1",
    },
    {
      id: "v2",
      placeId: "p3",
      date: daysAgo(15),
      meal: "middag",
      participantIds: ["m1", "m2", "m4"],
      overall: 4,
      taste: 5,
      value: 4,
      service: 3,
      comment: "Tacos runt bordet och lagom stökig fredagskänsla.",
      createdBy: "m2",
    },
    {
      id: "v3",
      placeId: "p6",
      date: daysAgo(29),
      meal: "middag",
      participantIds: ["m1", "m2", "m3", "m4", "m5"],
      overall: 4,
      taste: 4,
      value: 3,
      service: 4,
      comment: "Första kvällen på länge med hela gänget samlat.",
      createdBy: "m5",
    },
    {
      id: "v4",
      placeId: "p1",
      date: daysAgo(47),
      meal: "middag",
      participantIds: ["m2", "m3", "m5"],
      overall: 4,
      taste: 4,
      value: 4,
      service: 4,
      createdBy: "m3",
    },
    {
      id: "v5",
      placeId: "p4",
      date: daysAgo(62),
      meal: "frukost",
      participantIds: ["m1", "m4"],
      overall: 5,
      taste: 5,
      value: 4,
      service: 4,
      comment: "Tidigt, varmt bröd och nästan ingen kö.",
      createdBy: "m4",
    },
    {
      id: "v6",
      placeId: "p2",
      date: daysAgo(96),
      meal: "fika",
      participantIds: ["m1", "m2", "m3"],
      overall: 4,
      taste: 5,
      value: 3,
      service: 4,
      comment: "Återbesöket gjorde Pascal till ett av gruppens fikafavoriter.",
      createdBy: "m3",
    },
    {
      id: "v7",
      placeId: "p7",
      date: daysAgo(23),
      meal: "lunch",
      participantIds: ["m2", "m5"],
      overall: 4,
      taste: 4,
      value: 5,
      service: 4,
      createdBy: "m5",
    },
  ],
  favorites: [
    { memberId: "m1", placeId: "p2" },
    { memberId: "m3", placeId: "p2" },
    { memberId: "m1", placeId: "p5" },
    { memberId: "m2", placeId: "p3" },
    { memberId: "m4", placeId: "p4" },
    { memberId: "m5", placeId: "p7" },
  ],
  activity: [
    {
      id: "a1",
      kind: "visited",
      memberId: "m1",
      placeId: "p2",
      visitId: "v1",
      at: daysAgo(6),
      text: "Alex registrerade ett besök på Café Pascal",
      target: { kind: "visit", placeId: "p2", visitId: "v1" },
    },
    {
      id: "a2",
      kind: "next-picked",
      memberId: "m2",
      placeId: "p5",
      at: daysAgo(3),
      text: "Sam valde Hermans som nästa stopp",
      target: { kind: "place", placeId: "p5" },
    },
    {
      id: "a3",
      kind: "added",
      memberId: "m1",
      placeId: "p8",
      at: daysAgo(34),
      text: "Alex la till K25",
      target: { kind: "place", placeId: "p8" },
    },
    {
      id: "a4",
      kind: "visited",
      memberId: "m5",
      placeId: "p7",
      visitId: "v7",
      at: daysAgo(23),
      text: "Noor registrerade ett besök på Falloumi",
      target: { kind: "visit", placeId: "p7", visitId: "v7" },
    },
    {
      id: "a5",
      kind: "member-joined",
      memberId: "m5",
      at: daysAgo(180),
      text: "Noor gick med i gänget",
      target: { kind: "member", memberId: "m5" },
    },
  ],
  nextPlaceId: "p5",
};
