/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatstallenRouteImport } from './routes/matstallen'
import { Route as GruppenRouteImport } from './routes/gruppen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatstallenPlaceIdRouteImport } from './routes/matstallen.$placeId'
import { Route as InbjudanTokenRouteImport } from './routes/inbjudan.$token'

const MatstallenRoute = MatstallenRouteImport.update({
  id: '/matstallen',
  path: '/matstallen',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppenRoute = GruppenRouteImport.update({
  id: '/gruppen',
  path: '/gruppen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatstallenPlaceIdRoute = MatstallenPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => MatstallenRoute,
} as any)
const InbjudanTokenRoute = InbjudanTokenRouteImport.update({
  id: '/inbjudan/$token',
  path: '/inbjudan/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gruppen': typeof GruppenRoute
  '/matstallen': typeof MatstallenRouteWithChildren
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/matstallen/$placeId': typeof MatstallenPlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gruppen': typeof GruppenRoute
  '/matstallen': typeof MatstallenRouteWithChildren
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/matstallen/$placeId': typeof MatstallenPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gruppen': typeof GruppenRoute
  '/matstallen': typeof MatstallenRouteWithChildren
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/matstallen/$placeId': typeof MatstallenPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gruppen'
    | '/matstallen'
    | '/inbjudan/$token'
    | '/matstallen/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gruppen'
    | '/matstallen'
    | '/inbjudan/$token'
    | '/matstallen/$placeId'
  id:
    | '__root__'
    | '/'
    | '/gruppen'
    | '/matstallen'
    | '/inbjudan/$token'
    | '/matstallen/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GruppenRoute: typeof GruppenRoute
  MatstallenRoute: typeof MatstallenRouteWithChildren
  InbjudanTokenRoute: typeof InbjudanTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matstallen': {
      id: '/matstallen'
      path: '/matstallen'
      fullPath: '/matstallen'
      preLoaderRoute: typeof MatstallenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppen': {
      id: '/gruppen'
      path: '/gruppen'
      fullPath: '/gruppen'
      preLoaderRoute: typeof GruppenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matstallen/$placeId': {
      id: '/matstallen/$placeId'
      path: '/$placeId'
      fullPath: '/matstallen/$placeId'
      preLoaderRoute: typeof MatstallenPlaceIdRouteImport
      parentRoute: typeof MatstallenRoute
    }
    '/inbjudan/$token': {
      id: '/inbjudan/$token'
      path: '/inbjudan/$token'
      fullPath: '/inbjudan/$token'
      preLoaderRoute: typeof InbjudanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MatstallenRouteChildren {
  MatstallenPlaceIdRoute: typeof MatstallenPlaceIdRoute
}

const MatstallenRouteChildren: MatstallenRouteChildren = {
  MatstallenPlaceIdRoute: MatstallenPlaceIdRoute,
}

const MatstallenRouteWithChildren = MatstallenRoute._addFileChildren(
  MatstallenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GruppenRoute: GruppenRoute,
  MatstallenRoute: MatstallenRouteWithChildren,
  InbjudanTokenRoute: InbjudanTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
