/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BesokRouteImport } from './routes/besok'
import { Route as ExempelRouteImport } from './routes/exempel'
import { Route as GruppenRouteImport } from './routes/gruppen'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as MapdiagnostikRouteImport } from './routes/mapdiagnostik'
import { Route as MatstallenRouteImport } from './routes/matstallen'
import { Route as NyttLosenordRouteImport } from './routes/nytt-losenord'
import { Route as PlacemapdiagnostikRouteImport } from './routes/placemapdiagnostik'
import { Route as PlatsunderhallRouteImport } from './routes/platsunderhall'
import { Route as RapporteradeFelRouteImport } from './routes/rapporterade-fel'
import { Route as InbjudanTokenRouteImport } from './routes/inbjudan.$token'
import { Route as MatstallenPlaceIdRouteImport } from './routes/matstallen.$placeId'
import { Route as ApiPublicHooksPushDispatchRouteImport } from './routes/api/public/hooks/push-dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BesokRoute = BesokRouteImport.update({
  id: '/besok',
  path: '/besok',
  getParentRoute: () => rootRouteImport,
} as any)
const ExempelRoute = ExempelRouteImport.update({
  id: '/exempel',
  path: '/exempel',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppenRoute = GruppenRouteImport.update({
  id: '/gruppen',
  path: '/gruppen',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const MapdiagnostikRoute = MapdiagnostikRouteImport.update({
  id: '/mapdiagnostik',
  path: '/mapdiagnostik',
  getParentRoute: () => rootRouteImport,
} as any)
const MatstallenRoute = MatstallenRouteImport.update({
  id: '/matstallen',
  path: '/matstallen',
  getParentRoute: () => rootRouteImport,
} as any)
const NyttLosenordRoute = NyttLosenordRouteImport.update({
  id: '/nytt-losenord',
  path: '/nytt-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacemapdiagnostikRoute = PlacemapdiagnostikRouteImport.update({
  id: '/placemapdiagnostik',
  path: '/placemapdiagnostik',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatsunderhallRoute = PlatsunderhallRouteImport.update({
  id: '/platsunderhall',
  path: '/platsunderhall',
  getParentRoute: () => rootRouteImport,
} as any)
const RapporteradeFelRoute = RapporteradeFelRouteImport.update({
  id: '/rapporterade-fel',
  path: '/rapporterade-fel',
  getParentRoute: () => rootRouteImport,
} as any)
const InbjudanTokenRoute = InbjudanTokenRouteImport.update({
  id: '/inbjudan/$token',
  path: '/inbjudan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MatstallenPlaceIdRoute = MatstallenPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => MatstallenRoute,
} as any)
const ApiPublicHooksPushDispatchRoute =
  ApiPublicHooksPushDispatchRouteImport.update({
    id: '/api/public/hooks/push-dispatch',
    path: '/api/public/hooks/push-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/besok': typeof BesokRoute
  '/exempel': typeof ExempelRoute
  '/gruppen': typeof GruppenRoute
  '/integritet': typeof IntegritetRoute
  '/mapdiagnostik': typeof MapdiagnostikRoute
  '/matstallen': typeof MatstallenRouteWithChildren
  '/nytt-losenord': typeof NyttLosenordRoute
  '/placemapdiagnostik': typeof PlacemapdiagnostikRoute
  '/platsunderhall': typeof PlatsunderhallRoute
  '/rapporterade-fel': typeof RapporteradeFelRoute
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/matstallen/$placeId': typeof MatstallenPlaceIdRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/besok': typeof BesokRoute
  '/exempel': typeof ExempelRoute
  '/gruppen': typeof GruppenRoute
  '/integritet': typeof IntegritetRoute
  '/mapdiagnostik': typeof MapdiagnostikRoute
  '/matstallen': typeof MatstallenRouteWithChildren
  '/nytt-losenord': typeof NyttLosenordRoute
  '/placemapdiagnostik': typeof PlacemapdiagnostikRoute
  '/platsunderhall': typeof PlatsunderhallRoute
  '/rapporterade-fel': typeof RapporteradeFelRoute
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/matstallen/$placeId': typeof MatstallenPlaceIdRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/besok': typeof BesokRoute
  '/exempel': typeof ExempelRoute
  '/gruppen': typeof GruppenRoute
  '/integritet': typeof IntegritetRoute
  '/mapdiagnostik': typeof MapdiagnostikRoute
  '/matstallen': typeof MatstallenRouteWithChildren
  '/nytt-losenord': typeof NyttLosenordRoute
  '/placemapdiagnostik': typeof PlacemapdiagnostikRoute
  '/platsunderhall': typeof PlatsunderhallRoute
  '/rapporterade-fel': typeof RapporteradeFelRoute
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/matstallen/$placeId': typeof MatstallenPlaceIdRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/besok'
    | '/exempel'
    | '/gruppen'
    | '/integritet'
    | '/mapdiagnostik'
    | '/matstallen'
    | '/nytt-losenord'
    | '/placemapdiagnostik'
    | '/platsunderhall'
    | '/rapporterade-fel'
    | '/inbjudan/$token'
    | '/matstallen/$placeId'
    | '/api/public/hooks/push-dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/besok'
    | '/exempel'
    | '/gruppen'
    | '/integritet'
    | '/mapdiagnostik'
    | '/matstallen'
    | '/nytt-losenord'
    | '/placemapdiagnostik'
    | '/platsunderhall'
    | '/rapporterade-fel'
    | '/inbjudan/$token'
    | '/matstallen/$placeId'
    | '/api/public/hooks/push-dispatch'
  id:
    | '__root__'
    | '/'
    | '/besok'
    | '/exempel'
    | '/gruppen'
    | '/integritet'
    | '/mapdiagnostik'
    | '/matstallen'
    | '/nytt-losenord'
    | '/placemapdiagnostik'
    | '/platsunderhall'
    | '/rapporterade-fel'
    | '/inbjudan/$token'
    | '/matstallen/$placeId'
    | '/api/public/hooks/push-dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BesokRoute: typeof BesokRoute
  ExempelRoute: typeof ExempelRoute
  GruppenRoute: typeof GruppenRoute
  IntegritetRoute: typeof IntegritetRoute
  MapdiagnostikRoute: typeof MapdiagnostikRoute
  MatstallenRoute: typeof MatstallenRouteWithChildren
  NyttLosenordRoute: typeof NyttLosenordRoute
  PlacemapdiagnostikRoute: typeof PlacemapdiagnostikRoute
  PlatsunderhallRoute: typeof PlatsunderhallRoute
  RapporteradeFelRoute: typeof RapporteradeFelRoute
  InbjudanTokenRoute: typeof InbjudanTokenRoute
  ApiPublicHooksPushDispatchRoute: typeof ApiPublicHooksPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/besok': {
      id: '/besok'
      path: '/besok'
      fullPath: '/besok'
      preLoaderRoute: typeof BesokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exempel': {
      id: '/exempel'
      path: '/exempel'
      fullPath: '/exempel'
      preLoaderRoute: typeof ExempelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppen': {
      id: '/gruppen'
      path: '/gruppen'
      fullPath: '/gruppen'
      preLoaderRoute: typeof GruppenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapdiagnostik': {
      id: '/mapdiagnostik'
      path: '/mapdiagnostik'
      fullPath: '/mapdiagnostik'
      preLoaderRoute: typeof MapdiagnostikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matstallen': {
      id: '/matstallen'
      path: '/matstallen'
      fullPath: '/matstallen'
      preLoaderRoute: typeof MatstallenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nytt-losenord': {
      id: '/nytt-losenord'
      path: '/nytt-losenord'
      fullPath: '/nytt-losenord'
      preLoaderRoute: typeof NyttLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placemapdiagnostik': {
      id: '/placemapdiagnostik'
      path: '/placemapdiagnostik'
      fullPath: '/placemapdiagnostik'
      preLoaderRoute: typeof PlacemapdiagnostikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platsunderhall': {
      id: '/platsunderhall'
      path: '/platsunderhall'
      fullPath: '/platsunderhall'
      preLoaderRoute: typeof PlatsunderhallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapporterade-fel': {
      id: '/rapporterade-fel'
      path: '/rapporterade-fel'
      fullPath: '/rapporterade-fel'
      preLoaderRoute: typeof RapporteradeFelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbjudan/$token': {
      id: '/inbjudan/$token'
      path: '/inbjudan/$token'
      fullPath: '/inbjudan/$token'
      preLoaderRoute: typeof InbjudanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matstallen/$placeId': {
      id: '/matstallen/$placeId'
      path: '/$placeId'
      fullPath: '/matstallen/$placeId'
      preLoaderRoute: typeof MatstallenPlaceIdRouteImport
      parentRoute: typeof MatstallenRoute
    }
    '/api/public/hooks/push-dispatch': {
      id: '/api/public/hooks/push-dispatch'
      path: '/api/public/hooks/push-dispatch'
      fullPath: '/api/public/hooks/push-dispatch'
      preLoaderRoute: typeof ApiPublicHooksPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MatstallenRouteChildren {
  MatstallenPlaceIdRoute: typeof MatstallenPlaceIdRoute
}

const MatstallenRouteChildren: MatstallenRouteChildren = {
  MatstallenPlaceIdRoute: MatstallenPlaceIdRoute,
}

const MatstallenRouteWithChildren = MatstallenRoute._addFileChildren(
  MatstallenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BesokRoute: BesokRoute,
  ExempelRoute: ExempelRoute,
  GruppenRoute: GruppenRoute,
  IntegritetRoute: IntegritetRoute,
  MapdiagnostikRoute: MapdiagnostikRoute,
  MatstallenRoute: MatstallenRouteWithChildren,
  NyttLosenordRoute: NyttLosenordRoute,
  PlacemapdiagnostikRoute: PlacemapdiagnostikRoute,
  PlatsunderhallRoute: PlatsunderhallRoute,
  RapporteradeFelRoute: RapporteradeFelRoute,
  InbjudanTokenRoute: InbjudanTokenRoute,
  ApiPublicHooksPushDispatchRoute: ApiPublicHooksPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
