// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpihfmwbubvdiaavtpia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaWhmbXdidWJ2ZGlhYXZ0cGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMjIzNTgsImV4cCI6MjEwMjU5ODM1OH0.fANhpAImtZ_JyvNGyuxfEF1aoOV9ARKGq8LQeubpgR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});